---
steps:
  # Step 1: Build Docker Image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'us-central1-docker.pkg.dev/halogen-order-447007-t3/terraform/jenkinsimage:latest'
      - '.'

  # Step 2: Push Docker Image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'us-central1-docker.pkg.dev/halogen-order-447007-t3/terraform/jenkinsimage:latest'

  # Step 3: Deploy a release in Cloud Deploy
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - >
        gcloud deploy releases create release-$SHORT_SHA
        --delivery-pipeline=private-gke-deploy
        --region=us-central1
        --source=.
        --images="us-central1-docker.pkg.dev/halogen-order-447007-t3/terraform/jenkinsimage:latest=us-central1-docker.pkg.dev/halogen-order-447007-t3/terraform/jenkinsimage:latest"

