apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: dev
  annotations: {}
  labels: {}
description: dev
gke:
  cluster: projects/halogen-order-447007-t3/locations/asia-south2-a/clusters/my-gke-cluster
  
  
